// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/go-kratos/kratos/v2"
	"github.com/hibiken/asynq"
	asynq2 "github.com/justblue/luoye/kit/messaging/asynq"
	"github.com/justblue/luoye/kit/messaging/nats"
	"github.com/justblue/luoye/services/goodbye/internal/conf"
	"github.com/justblue/luoye/services/goodbye/internal/event"
	"github.com/justblue/luoye/services/goodbye/internal/grpchandler"
	"github.com/justblue/luoye/services/goodbye/internal/server"
	"github.com/justblue/luoye/services/goodbye/internal/usecase"
	"github.com/nats-io/nats.go/jetstream"
)

// Injectors from wire.go:

func initApp(cfg *conf.Config) (*kratos.App, func(), error) {
	client, err := provideNATSClient(cfg)
	if err != nil {
		return nil, nil, err
	}
	publisher, err := event.NewPublisher(client)
	if err != nil {
		return nil, nil, err
	}
	asynqClient := provideAsynqClient(cfg)
	asynqPublisher := event.NewAsynqPublisher(asynqClient)
	compositePublisher := event.NewCompositePublisher(publisher, asynqPublisher)
	goodbyeService := usecase.NewGoodbyeService(compositePublisher)
	goodbyeServer := grpchandler.NewGoodbyeServer(goodbyeService)
	httpServer := server.NewHTTPServer(cfg, goodbyeServer)
	grpcServer := server.NewGRPCServer(cfg, goodbyeServer)
	app := server.NewApp(httpServer, grpcServer)
	return app, func() {
	}, nil
}

// wire.go:

func provideNATSClient(cfg *conf.Config) (*nats.Client, error) {
	client, err := nats.NewClient(cfg.NATS.URL)
	if err != nil {
		return nil, err
	}
	if err := client.EnsureStream(context.Background(), "goodbye", []string{"goodbye.said"}, jetstream.MemoryStorage); err != nil {
		client.Close()
		return nil, err
	}
	return client, nil
}

func provideAsynqClient(cfg *conf.Config) *asynq.Client {
	return asynq2.NewClient(asynq2.Config{Addr: cfg.Redis.Addr})
}
