// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/justblue/luoye/kit/messaging/nats"
	"github.com/justblue/luoye/services/hello/internal/conf"
	"github.com/justblue/luoye/services/hello/internal/event"
	"github.com/justblue/luoye/services/hello/internal/grpcclient"
	"github.com/justblue/luoye/services/hello/internal/grpchandler"
	"github.com/justblue/luoye/services/hello/internal/server"
	"github.com/justblue/luoye/services/hello/internal/usecase"
)

// Injectors from wire.go:

func initApp(cfg *conf.Config) (*kratos.App, func(), error) {
	upstreamConfig := provideUpstream(cfg)
	goodbyeClient, err := grpcclient.NewGoodbyeClient(upstreamConfig)
	if err != nil {
		return nil, nil, err
	}
	greeterService := usecase.NewGreeterService(goodbyeClient)
	greeterServer := grpchandler.NewGreeterServer(greeterService)
	httpServer := server.NewHTTPServer(cfg, greeterServer)
	grpcServer := server.NewGRPCServer(cfg, greeterServer)
	client, cleanupNATS, err := provideNATSClient(cfg)
	if err != nil {
		return nil, nil, err
	}
	consumer, err := event.NewConsumer(client)
	if err != nil {
		cleanupNATS()
		return nil, nil, err
	}
	app := server.NewApp(httpServer, grpcServer, consumer)
	return app, func() {
		cleanupNATS()
	}, nil
}

// wire.go:

func provideNATSClient(cfg *conf.Config) (*nats.Client, func(), error) {
	client, err := nats.NewClient(cfg.NATS.URL)
	if err != nil {
		return nil, nil, err
	}
	return client, func() { client.Close() }, nil
}

func provideUpstream(cfg *conf.Config) conf.UpstreamConfig { return cfg.Upstream }
