// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/hibiken/asynq"
	asynq2 "github.com/justblue/luoye/kit/messaging/asynq"
	"github.com/justblue/luoye/services/worker/internal/conf"
	"github.com/justblue/luoye/services/worker/internal/handler"
	"github.com/justblue/luoye/services/worker/internal/server"
)

// Injectors from wire.go:

func initApp(cfg *conf.Config) (*kratos.App, func(), error) {
	httpServer := server.NewHTTPServer(cfg)
	asynqServer := provideAsynqServer(cfg)
	goodbyeHandler := handler.NewGoodbyeHandler()
	asynqService := server.NewAsynqService(asynqServer, goodbyeHandler)
	app := server.NewApp(httpServer, asynqService)
	return app, func() {
	}, nil
}

// wire.go:

func provideAsynqServer(cfg *conf.Config) *asynq.Server {
	return asynq2.NewServer(asynq2.Config{Addr: cfg.Redis.Addr})
}
